// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

// Package s3iface provides an interface for the Amazon Simple Storage Service.
package s3iface

import (
	"github.com/ks3sdklib/aws-sdk-go/service/s3"
)

// S3API is the interface type for s3.S3.
type S3API interface {
	AbortMultipartUpload(*s3.AbortMultipartUploadInput) (*s3.AbortMultipartUploadOutput, error)

	AppendObject(input *s3.AppendObjectInput) (*s3.AppendObjectOutput, error)

	CompleteMultipartUpload(*s3.CompleteMultipartUploadInput) (*s3.CompleteMultipartUploadOutput, error)

	CopyObject(*s3.CopyObjectInput) (*s3.CopyObjectOutput, error)

	CreateBucket(*s3.CreateBucketInput) (*s3.CreateBucketOutput, error)

	CreateMultipartUpload(*s3.CreateMultipartUploadInput) (*s3.CreateMultipartUploadOutput, error)

	CreateJob(*s3.CreateJobInput) (*s3.CreateJobOutput, error)

	ClearObject(*s3.ClearObjectInput) (*s3.ClearObjectOutput, error)

	DeleteBucket(*s3.DeleteBucketInput) (*s3.DeleteBucketOutput, error)

	DeleteBucketCORS(*s3.DeleteBucketCORSInput) (*s3.DeleteBucketCORSOutput, error)

	DeleteBucketLifecycle(*s3.DeleteBucketLifecycleInput) (*s3.DeleteBucketLifecycleOutput, error)

	DeleteBucketNotification(*s3.DeleteBucketNotificationInput) (*s3.DeleteBucketNotificationOutput, error)

	DeleteBucketPolicy(*s3.DeleteBucketPolicyInput) (*s3.DeleteBucketPolicyOutput, error)

	DeleteBucketReplication(*s3.DeleteBucketReplicationInput) (*s3.DeleteBucketReplicationOutput, error)

	DeleteBucketTagging(*s3.DeleteBucketTaggingInput) (*s3.DeleteBucketTaggingOutput, error)

	DeleteBucketWebsite(*s3.DeleteBucketWebsiteInput) (*s3.DeleteBucketWebsiteOutput, error)

	DeleteBucketDecompressPolicy(*s3.DeleteBucketDecompressPolicyInput) (*s3.DeleteBucketDecompressPolicyOutput, error)

	DeleteBucketInventory(*s3.DeleteBucketInventoryInput) (*s3.DeleteBucketInventoryOutput, error)

	DeleteBucketQos(*s3.DeleteBucketQosInput) (*s3.DeleteBucketQosOutput, error)

	DeleteRequesterQos(*s3.DeleteRequesterQosInput) (*s3.DeleteRequesterQosOutput, error)

	DeleteBucketEncryption(*s3.DeleteBucketEncryptionInput) (*s3.DeleteBucketEncryptionOutput, error)

	DeleteVpcAccessBlock(*s3.DeleteVpcAccessBlockInput) (*s3.DeleteVpcAccessBlockOutput, error)

	DeleteBucketQuota(*s3.DeleteBucketQuotaInput) (*s3.DeleteBucketQuotaOutput, error)

	DeleteObject(*s3.DeleteObjectInput) (*s3.DeleteObjectOutput, error)

	DeleteObjects(*s3.DeleteObjectsInput) (*s3.DeleteObjectsOutput, error)

	DeleteJob(*s3.DeleteJobInput) (*s3.DeleteJobOutput, error)

	DescribeJob(*s3.DescribeJobInput) (*s3.DescribeJobOutput, error)

	GetBucketACL(*s3.GetBucketACLInput) (*s3.GetBucketACLOutput, error)

	GetBucketCORS(*s3.GetBucketCORSInput) (*s3.GetBucketCORSOutput, error)

	GetBucketLifecycle(*s3.GetBucketLifecycleInput) (*s3.GetBucketLifecycleOutput, error)

	GetBucketAccessMonitor(*s3.GetBucketAccessMonitorInput) (*s3.GetBucketAccessMonitorOutput, error)

	GetBucketLocation(*s3.GetBucketLocationInput) (*s3.GetBucketLocationOutput, error)

	GetBucketLogging(*s3.GetBucketLoggingInput) (*s3.GetBucketLoggingOutput, error)

	GetBucketNotification(*s3.GetBucketNotificationInput) (*s3.GetBucketNotificationOutput, error)

	GetBucketPolicy(*s3.GetBucketPolicyInput) (*s3.GetBucketPolicyOutput, error)

	GetBucketReplication(*s3.GetBucketReplicationInput) (*s3.GetBucketReplicationOutput, error)

	GetBucketRequestPayment(*s3.GetBucketRequestPaymentInput) (*s3.GetBucketRequestPaymentOutput, error)

	GetBucketTagging(*s3.GetBucketTaggingInput) (*s3.GetBucketTaggingOutput, error)

	GetBucketVersioning(*s3.GetBucketVersioningInput) (*s3.GetBucketVersioningOutput, error)

	GetBucketWebsite(*s3.GetBucketWebsiteInput) (*s3.GetBucketWebsiteOutput, error)

	GetBucketDecompressPolicy(*s3.GetBucketDecompressPolicyInput) (*s3.GetBucketDecompressPolicyOutput, error)

	GetBucketRetention(*s3.GetBucketRetentionInput) (*s3.GetBucketRetentionOutput, error)

	GetBucketInventory(*s3.GetBucketInventoryInput) (*s3.GetBucketInventoryOutput, error)

	GetBucketDataRedundancySwitch(*s3.GetBucketDataRedundancySwitchInput) (*s3.GetBucketDataRedundancySwitchOutput, error)

	GetBucketQos(*s3.GetBucketQosInput) (*s3.GetBucketQosOutput, error)

	GetRequesterQos(*s3.GetRequesterQosInput) (*s3.GetRequesterQosOutput, error)

	GetBucketEncryption(*s3.GetBucketEncryptionInput) (*s3.GetBucketEncryptionOutput, error)

	GetBucketTransferAcceleration(*s3.GetBucketTransferAccelerationInput) (*s3.GetBucketTransferAccelerationOutput, error)

	GetVpcAccessBlock(*s3.GetVpcAccessBlockInput) (*s3.GetVpcAccessBlockOutput, error)

	GetBucketQuota(*s3.GetBucketQuotaInput) (*s3.GetBucketQuotaOutput, error)

	GetObject(*s3.GetObjectInput) (*s3.GetObjectOutput, error)

	GetObjectMigration(*s3.GetObjectMigrationInput) (*s3.GetObjectMigrationOutput, error)

	GetObjectACL(*s3.GetObjectACLInput) (*s3.GetObjectACLOutput, error)

	GetObjectTorrent(*s3.GetObjectTorrentInput) (*s3.GetObjectTorrentOutput, error)

	HeadBucket(*s3.HeadBucketInput) (*s3.HeadBucketOutput, error)

	HeadObject(*s3.HeadObjectInput) (*s3.HeadObjectOutput, error)

	ListBuckets(*s3.ListBucketsInput) (*s3.ListBucketsOutput, error)

	ListMultipartUploads(*s3.ListMultipartUploadsInput) (*s3.ListMultipartUploadsOutput, error)

	ListObjectVersions(*s3.ListObjectVersionsInput) (*s3.ListObjectVersionsOutput, error)

	ListObjects(*s3.ListObjectsInput) (*s3.ListObjectsOutput, error)

	ListParts(*s3.ListPartsInput) (*s3.ListPartsOutput, error)

	ListRetention(*s3.ListRetentionInput) (*s3.ListRetentionOutput, error)

	ListBucketInventory(*s3.ListBucketInventoryInput) (*s3.ListBucketInventoryOutput, error)

	ListJobs(*s3.ListJobsInput) (*s3.ListJobsOutput, error)

	PutBucketACL(*s3.PutBucketACLInput) (*s3.PutBucketACLOutput, error)

	PutBucketCORS(*s3.PutBucketCORSInput) (*s3.PutBucketCORSOutput, error)

	PutBucketLifecycle(*s3.PutBucketLifecycleInput) (*s3.PutBucketLifecycleOutput, error)

	PutBucketAccessMonitor(*s3.PutBucketAccessMonitorInput) (*s3.PutBucketAccessMonitorOutput, error)

	PutBucketLogging(*s3.PutBucketLoggingInput) (*s3.PutBucketLoggingOutput, error)

	PutBucketNotification(*s3.PutBucketNotificationInput) (*s3.PutBucketNotificationOutput, error)

	PutBucketPolicy(*s3.PutBucketPolicyInput) (*s3.PutBucketPolicyOutput, error)

	PutBucketReplication(*s3.PutBucketReplicationInput) (*s3.PutBucketReplicationOutput, error)

	PutBucketRequestPayment(*s3.PutBucketRequestPaymentInput) (*s3.PutBucketRequestPaymentOutput, error)

	PutBucketTagging(*s3.PutBucketTaggingInput) (*s3.PutBucketTaggingOutput, error)

	PutBucketVersioning(*s3.PutBucketVersioningInput) (*s3.PutBucketVersioningOutput, error)

	PutBucketWebsite(*s3.PutBucketWebsiteInput) (*s3.PutBucketWebsiteOutput, error)

	PutBucketDecompressPolicy(*s3.PutBucketDecompressPolicyInput) (*s3.PutBucketDecompressPolicyOutput, error)

	PutBucketRetention(*s3.PutBucketRetentionInput) (*s3.PutBucketRetentionOutput, error)

	PutBucketInventory(*s3.PutBucketInventoryInput) (*s3.PutBucketInventoryOutput, error)

	PutBucketDataRedundancySwitch(*s3.PutBucketDataRedundancySwitchInput) (*s3.PutBucketDataRedundancySwitchOutput, error)

	PutBucketQos(*s3.PutBucketQosInput) (*s3.PutBucketQosOutput, error)

	PutRequesterQos(*s3.PutRequesterQosInput) (*s3.PutRequesterQosOutput, error)

	PutBucketEncryption(*s3.PutBucketEncryptionInput) (*s3.PutBucketEncryptionOutput, error)

	PutBucketTransferAcceleration(*s3.PutBucketTransferAccelerationInput) (*s3.PutBucketTransferAccelerationOutput, error)

	PutVpcAccessBlock(*s3.PutVpcAccessBlockInput) (*s3.PutVpcAccessBlockOutput, error)

	PutBucketQuota(*s3.PutBucketQuotaInput) (*s3.PutBucketQuotaOutput, error)

	PutObject(*s3.PutObjectInput) (*s3.PutObjectOutput, error)

	PutObjectMigration(*s3.PutObjectMigrationInput) (*s3.PutObjectMigrationOutput, error)

	PutObjectACL(*s3.PutObjectACLInput) (*s3.PutObjectACLOutput, error)

	RestoreObject(*s3.RestoreObjectInput) (*s3.RestoreObjectOutput, error)

	RecoverObject(*s3.RecoverObjectInput) (*s3.RecoverObjectOutput, error)

	UploadPart(*s3.UploadPartInput) (*s3.UploadPartOutput, error)

	UploadPartCopy(*s3.UploadPartCopyInput) (*s3.UploadPartCopyOutput, error)

	UpdateJobPriority(*s3.UpdateJobPriorityInput) (*s3.UpdateJobPriorityOutput, error)
}
